TAG: 'temporal'

DATASET:
    TRAIN_DATA: ['dataset/zed2/data_train', 'dataset/realsense/data_train']
    VALID_DATA: ['dataset/zed2/data_valid', 'dataset/realsense/data_valid']

TRAINING:
    BATCHSIZE: 8
    WORKERS: 4
    EPOCHS: 50
    VERBOSE: False

MODEL:
    TIME_LENGTH: 6
    DOWNSAMPLE: 4
    LATENT_DIM: 64
    INPUT_SIZE: [160, 90]
    PREDICT_DEPTH: True
    TRAIN_DEPTH: True
    FUSE_PCLOUD: True
    GRID_BOUNDS: {
        'xbound': [-2.0, 8.0, 0.1],
        'ybound': [-5.0, 5.0, 0.1],
        'zbound': [-1.0, 2.0, 1.0],
        'dbound': [ 0.3, 8.0, 0.3]}
